//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ModelClass.WS_800126 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Add_NMPOperationCompleted;
        
        private System.Threading.SendOrPostCallback Remove_NMPOperationCompleted;
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback sendsmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SmsMTOperationCompleted;
        
        private System.Threading.SendOrPostCallback SMSMO8x83OperationCompleted;
        
        private System.Threading.SendOrPostCallback AccstatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsByGroupOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::ModelClass.Properties.Settings.Default.ModelClass_WS_800126_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Add_NMPCompletedEventHandler Add_NMPCompleted;
        
        /// <remarks/>
        public event Remove_NMPCompletedEventHandler Remove_NMPCompleted;
        
        /// <remarks/>
        public event sendsmsCompletedEventHandler sendsmsCompleted;
        
        /// <remarks/>
        public event SmsMTCompletedEventHandler SmsMTCompleted;
        
        /// <remarks/>
        public event SMSMO8x83CompletedEventHandler SMSMO8x83Completed;
        
        /// <remarks/>
        public event AccstatusCompletedEventHandler AccstatusCompleted;
        
        /// <remarks/>
        public event SendSmsByGroupCompletedEventHandler SendSmsByGroupCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Add_NMP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Add_NMP(string username, string password, string phonenumber) {
            object[] results = this.Invoke("Add_NMP", new object[] {
                        username,
                        password,
                        phonenumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Add_NMPAsync(string username, string password, string phonenumber) {
            this.Add_NMPAsync(username, password, phonenumber, null);
        }
        
        /// <remarks/>
        public void Add_NMPAsync(string username, string password, string phonenumber, object userState) {
            if ((this.Add_NMPOperationCompleted == null)) {
                this.Add_NMPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdd_NMPOperationCompleted);
            }
            this.InvokeAsync("Add_NMP", new object[] {
                        username,
                        password,
                        phonenumber}, this.Add_NMPOperationCompleted, userState);
        }
        
        private void OnAdd_NMPOperationCompleted(object arg) {
            if ((this.Add_NMPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Add_NMPCompleted(this, new Add_NMPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Remove_NMP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Remove_NMP(string username, string password, string phonenumber) {
            object[] results = this.Invoke("Remove_NMP", new object[] {
                        username,
                        password,
                        phonenumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Remove_NMPAsync(string username, string password, string phonenumber) {
            this.Remove_NMPAsync(username, password, phonenumber, null);
        }
        
        /// <remarks/>
        public void Remove_NMPAsync(string username, string password, string phonenumber, object userState) {
            if ((this.Remove_NMPOperationCompleted == null)) {
                this.Remove_NMPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemove_NMPOperationCompleted);
            }
            this.InvokeAsync("Remove_NMP", new object[] {
                        username,
                        password,
                        phonenumber}, this.Remove_NMPOperationCompleted, userState);
        }
        
        private void OnRemove_NMPOperationCompleted(object arg) {
            if ((this.Remove_NMPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Remove_NMPCompleted(this, new Remove_NMPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sendsms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sendsms(string sdt, string infor) {
            object[] results = this.Invoke("sendsms", new object[] {
                        sdt,
                        infor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendsmsAsync(string sdt, string infor) {
            this.sendsmsAsync(sdt, infor, null);
        }
        
        /// <remarks/>
        public void sendsmsAsync(string sdt, string infor, object userState) {
            if ((this.sendsmsOperationCompleted == null)) {
                this.sendsmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendsmsOperationCompleted);
            }
            this.InvokeAsync("sendsms", new object[] {
                        sdt,
                        infor}, this.sendsmsOperationCompleted, userState);
        }
        
        private void OnsendsmsOperationCompleted(object arg) {
            if ((this.sendsmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendsmsCompleted(this, new sendsmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SmsMT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SmsMT(string user, string pass, string sdt, string infor) {
            object[] results = this.Invoke("SmsMT", new object[] {
                        user,
                        pass,
                        sdt,
                        infor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SmsMTAsync(string user, string pass, string sdt, string infor) {
            this.SmsMTAsync(user, pass, sdt, infor, null);
        }
        
        /// <remarks/>
        public void SmsMTAsync(string user, string pass, string sdt, string infor, object userState) {
            if ((this.SmsMTOperationCompleted == null)) {
                this.SmsMTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSmsMTOperationCompleted);
            }
            this.InvokeAsync("SmsMT", new object[] {
                        user,
                        pass,
                        sdt,
                        infor}, this.SmsMTOperationCompleted, userState);
        }
        
        private void OnSmsMTOperationCompleted(object arg) {
            if ((this.SmsMTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SmsMTCompleted(this, new SmsMTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SMSMO8x83", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SMSMO8x83(string username, string password, string phonenumber, string message, string messageid) {
            object[] results = this.Invoke("SMSMO8x83", new object[] {
                        username,
                        password,
                        phonenumber,
                        message,
                        messageid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SMSMO8x83Async(string username, string password, string phonenumber, string message, string messageid) {
            this.SMSMO8x83Async(username, password, phonenumber, message, messageid, null);
        }
        
        /// <remarks/>
        public void SMSMO8x83Async(string username, string password, string phonenumber, string message, string messageid, object userState) {
            if ((this.SMSMO8x83OperationCompleted == null)) {
                this.SMSMO8x83OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSMSMO8x83OperationCompleted);
            }
            this.InvokeAsync("SMSMO8x83", new object[] {
                        username,
                        password,
                        phonenumber,
                        message,
                        messageid}, this.SMSMO8x83OperationCompleted, userState);
        }
        
        private void OnSMSMO8x83OperationCompleted(object arg) {
            if ((this.SMSMO8x83Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SMSMO8x83Completed(this, new SMSMO8x83CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Accstatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Accstatus(string taikhoan) {
            object[] results = this.Invoke("Accstatus", new object[] {
                        taikhoan});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AccstatusAsync(string taikhoan) {
            this.AccstatusAsync(taikhoan, null);
        }
        
        /// <remarks/>
        public void AccstatusAsync(string taikhoan, object userState) {
            if ((this.AccstatusOperationCompleted == null)) {
                this.AccstatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccstatusOperationCompleted);
            }
            this.InvokeAsync("Accstatus", new object[] {
                        taikhoan}, this.AccstatusOperationCompleted, userState);
        }
        
        private void OnAccstatusOperationCompleted(object arg) {
            if ((this.AccstatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccstatusCompleted(this, new AccstatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSmsByGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSmsByGroup(string username, string password, string groupname, string message) {
            object[] results = this.Invoke("SendSmsByGroup", new object[] {
                        username,
                        password,
                        groupname,
                        message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsByGroupAsync(string username, string password, string groupname, string message) {
            this.SendSmsByGroupAsync(username, password, groupname, message, null);
        }
        
        /// <remarks/>
        public void SendSmsByGroupAsync(string username, string password, string groupname, string message, object userState) {
            if ((this.SendSmsByGroupOperationCompleted == null)) {
                this.SendSmsByGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsByGroupOperationCompleted);
            }
            this.InvokeAsync("SendSmsByGroup", new object[] {
                        username,
                        password,
                        groupname,
                        message}, this.SendSmsByGroupOperationCompleted, userState);
        }
        
        private void OnSendSmsByGroupOperationCompleted(object arg) {
            if ((this.SendSmsByGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsByGroupCompleted(this, new SendSmsByGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Add_NMPCompletedEventHandler(object sender, Add_NMPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Add_NMPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Add_NMPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Remove_NMPCompletedEventHandler(object sender, Remove_NMPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Remove_NMPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Remove_NMPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sendsmsCompletedEventHandler(object sender, sendsmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendsmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendsmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SmsMTCompletedEventHandler(object sender, SmsMTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SmsMTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SmsMTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SMSMO8x83CompletedEventHandler(object sender, SMSMO8x83CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SMSMO8x83CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SMSMO8x83CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AccstatusCompletedEventHandler(object sender, AccstatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccstatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccstatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendSmsByGroupCompletedEventHandler(object sender, SendSmsByGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsByGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsByGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591